Update beep-boop via integrating p2panda-js-0.2.0
p2panda/beep-boop pull request #30
Opened 2021-10-15 16:12 UTC by sophiiistika

2021-11-23 09:56 UTC, adzialocha requested changes
Yay!

I think the whole `src/p2panda-api` folder can be deleted actually, its been there as a temporary API until `p2panda-js@0.2.0` got released :+1:

2021-11-23 15:40 UTC, cafca requested changes
I noticed that the example on the left hand-side is still using the old API. Otherwise good to go!

2021-12-06 09:34 UTC, adzialocha approved these changes
:space_invader:

2021-12-06 13:09 UTC, cafca approved these changes

2021-12-06 13:09 UTC, merged